# 
# Community
# A plugin for managing a Minecraft community
#
general:
  server-name: "&4Overcast &7Community" # Server display name used at various places


# Moderation - Settings related to punishments (/warn, /kick, /ban, /mute)
moderation:
  enabled: true   # Whether punishments are enabled
  persist: true   # Whether to save to database
  broadcast: true # Whether to broadcast punishments
  
  #Message options for kick screen
  rules-link: "https://pgm.dev/rules" #Link to rules
  appeal-link: "&7If this ban was made in error, contact &estaff@pgm.dev" # Appeal message (Only shown for perm-bans)
  
  #Punishments types - TODO: more options will be found under each punishment type  
  warn:
    enabled: true
  kick:
    enabled: true
  ban:
    enabled: true
  mute:
    enabled: true
  
   
# Reports - Settings related to /report and /reports
reports:
  enabled:  true   # Whether reports are enabled
  persist:  true   # Whether to save to database 
  cooldown: 15     # Duration of cooldown in seconds

# Users - Track user related info including, name/uuid, first/last logins, join count, and IP history
users:
  enabled: true
    
  
# Database
database:
  enabled: true # Whether to use a database (If false persistent features will not work)
  uri: ""
