# 
# Community
# A plugin for managing a Minecraft community
#
general:
  server-name: "&4Overcast &7Community" # Server display name used at various places


# Moderation - Settings related to punishments (/warn, /kick, /ban, /mute)
moderation:
  enabled: true   # Whether punishments are enabled
  persist: true   # Whether to save to database
  broadcast: true # Whether to broadcast punishments
  
  #Message options for kick screen
  rules-link: "https://pgm.dev/rules" #Link to rules
  appeal-link: "&7If this ban was made in error, contact &estaff@pgm.dev" # Appeal message (Only shown for perm-bans)
  
  #Punishments types - TODO: more options will be found under each punishment type  
  warn:
    enabled: true
  kick:
    enabled: true
  ban:
    enabled: true
  mute:
    enabled: true
  
   
# Reports - Settings related to /report and /reports
reports:
  enabled:  true   # Whether reports are enabled
  persist:  true   # Whether to save to database 
  cooldown: 15     # Duration of cooldown in seconds

# Users - Track user related info including, name/uuid, first/last logins, join count, and IP history
users:
  enabled: true
  
# Friends - Settings related to friendship features/commands  
friends:
  enabled: true
  
# Teleports - Teleport commands include /tp, /bring, and /tploc
teleports:
  enabled: true
  
# Chat Management - Commands that relate to chat management such as slowmode and lockdown
chat:
  enabled: true       # Whether chat management commands are enabled
  slowmode-speed: 30  # Cooldown time (in seconds) between messages during slowmode 
  login-alert: true   # Whether to alert joining players if slowmode or lockdown are enabeld
    
# Custom Info Commands    
commands:
  # Example of /rules command
  rules: # The command name is defined as the config section
    permission: "community.rules" # You can define any permission node, or use "" for no permission
    lines: # You can have an unlimited # of lines that will be sent to the player. & color code formatting supported
      - "&7&m-------&r &a&lServer Rules&f &7&m-------&r"
      - "&e1. &3Be Nice"
      - "&e2. &3No griefing"
      - "&e3. &3No cheating"
  # Second example of a single line /website command    
  website:
    permission: "" # For no permission, leave empty
    lines:
      - "&7Visit our website at &b&nhttps://pgm.dev"
  
# Database
database:
  enabled: true # Whether to use a database (If false persistent features will not work)
  uri: ""
