#Community Config
# Features are separated into categories

# Reports - Settings related to /report and /reports
reports:
  enabled:  true   # Whether reports are enabled
  persist:  false  # Whether to save to database 
  cooldown: 15     # Duration of cooldown in seconds
  